version: '3.8'
services:

  postgres:
    restart: always
    image: postgres:14.2
    environment:
      POSTGRES_DB: crossfit
      POSTGRES_USER: usr_crossfit
      POSTGRES_PASSWORD: an29ahAv_r2k
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data
    ports:
      - "5436:5432"

  migrate-up:
    image: migrate/migrate
    volumes:
      - ./migration:/migration
    command: ["-path", "/migration", "-database",  "postgres://usr_crossfit:an29ahAv_r2k@postgres/crossfit?sslmode=disable", "up"]

  backend:
    build:
      context: .
    ports:
      - 18080:8080
    volumes:
      - ./ugc:/ugc
    environment:
      HOST: postgres
      DB_PORT: 5432
      DB_NAME: crossfit
      DB_USERNAME: usr_crossfit
      DB_PASSWORD: an29ahAv_r2k
      SSL_MODE: disable
      STORAGE_PATH: /ugc