version: '3.8'
services:

  postgres:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data
    ports:
      - "5436:5432"
